### PR TITLE
Fix: check correctly the attribute we want to set

### PR DESCRIPTION
**Pull request by jeerbl**
Related to #58

### CODE REVIEW

**Comment by jeerbl** [comment]
Sorry to insist on this but, is this gonna be merged soon?

Cheers
Jerome

**Comment by jeerbl** [comment]
@Atinux any chance this gets merged soon?

**Comment by jeerbl** [comment]
Thanks @Atinux. I also saw there is no release since last december. Is it possible to release this on NPM?

Cheers
Jerome

**Comment by Atinux** [comment]
I am working on it actually @jeerbl :)

**Comment by jeerbl** [comment]
Very nice of you. Thanks a lot for this!

Jerome

**Pull request merged**
